/// Flutter icons OLReaderIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OLReaderIcons
///      fonts:
///       - asset: fonts/OLReaderIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OLReaderIcons {
  OLReaderIcons._();

  static const _kFontFam = 'OLReaderIcons';
  static const String? _kFontPkg = null;

  static const IconData clock = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unavailable = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dateOutline = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData date = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clockFilledOutline = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clockFilled = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
